export const action = {
  CONTROL_INCREMENT: 'CONTROL:INCREMENT',
  CONTROL_DECREMENT: 'CONTROL:DECREMENT',

  MODE_CHANGE: 'MODE:CHANGE',

  CELL_CLICK: 'CELL:CLICK',

  APP_UNMOUNT: 'APP:UNMOUNT'
};